apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-example02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: example-secret
    namespace: example02
    jsonPointers:
    - /data/my-password
  - group: apps
    version: v1
    name: simple-deployment
    namespace: example02
    kind: Deployment
    jsonPointers:
    - /metadata/annotations/creation
  project: default

  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./custom-diff/02-external-app
   
  destination:
    server: https://kubernetes.default.svc
    namespace: example02

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
