apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: problematic-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./custom-diff/applications
    repoURL: https://github.com/jimrobison/gitops-cert-level-2-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
